pkgs/spoldzielnie/src/spoldzielnie/routes/common.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, send_file, sessions, jsonify
import geojson
from spoldzielnie.models import Spoldzielnia, Sprawa, Walne
import csv
import pandas as pd
from os.path import join, dirname, realpath
from spoldzielnie import db
from datetime import datetime
from loguru import logger

STATIC_FOLDER = join(dirname(realpath(__file__)), '../static')
common = Blueprint('common', __name__)

@common.route('/favicon')
def favicon():
    return url_for('static', filename='favicon.ico')


@common.route('/', methods=['GET', 'POST'])
def main():
    logger.info(f"baza index : {db}")

    return render_template('index.html')


@common.route('/spoldzielnie', methods=['GET'])
def spoldzielnie():

    return render_template('spoldzielnia.html')

@common.route('/artykuly', methods=['GET'])
def artykuly():
    return render_template('artykuly.html')

@common.route('/artykuly_dane', methods=['GET'])
def artykuly_dane():

    logger.info(f"artykuly dane")
    logger.info(f"baza danych : {db}")

    result = db.session.query(Sprawa, Spoldzielnia).join(
        Spoldzielnia, Spoldzielnia.krs == Sprawa.spoldzielnia, 
        isouter=True).all()
    
    logger.info(f"artykuly dane result : {result}")


    S=[]
    for spr, s in result:

        S.append({
            'krs': s.krs if s else 'None',
            'nazwa': s.nazwa if s else '',
            'miejscowosc': s.miejscowosc if s else '',
            'data_rozpoczenia': spr.data_rozpoczenia,
            'temat': spr.temat,
            'typ': spr.typ,
            'opis': spr.opis,
            'status': spr.status,
            'rozwiazanie': spr.rozwiazanie,
            'odnosniki': spr.odnosniki


        }
            
        )

    return jsonify([s for s in S])


@common.route('/spoldzielnie_dane', methods=['GET'])
def spoldzielnie_dane():

    # query dane from Spoldzielnia and join bilans data from Walne by krs, show all columns

    #S = Spoldzielnia.query.join(Walne, Spoldzielnia.krs == Walne.spoldzielnia).all()
    result = db.session.query(Spoldzielnia, Walne).join(
        Walne, Walne.spoldzielnia == Spoldzielnia.krs, 
        isouter=True).all()

    
    S=[]
    for s, w in result:

        if w.rok == 2022:

            S.append({
                'krs': s.krs,
                'bilans': w.bilans if w else 'do sprawdzenia',
                'nazwa': s.nazwa,
                'szerokosc_geo': s.szerokosc_geo,
                'dlugosc_geo': s.dlugosc_geo,
                'kod_pocztowy': s.kod_pocztowy,
                'miejscowosc': s.miejscowosc,
                'dzielnica': s.dzielnica,
                'forma_prawna': s.forma_prawna,
                'data_rejestracji': s.data_rejestracji,
                'status': s.status,
                'nip': s.nip,
                'regon': s.regon,
                'adres': s.adres,

            }
                
            )


    #S = Spoldzielnia.query.order_by(Spoldzielnia.nazwa).all()
    return jsonify([s for s in S])

@common.route('/sprawy_dane', methods=['GET'])
def sprawy_dane():
    S = Sprawa.query.order_by(Sprawa.spoldzielnia).all()
    return jsonify([s.as_dict() for s in S])

@common.route('/walne_dane', methods=['GET'])
def walne_dane():
    S = Sprawa.query.order_by(Walne.spoldzielnia).all()
    return jsonify([s.as_dict() for s in S])

pkgs/spoldzielnie/src/spoldzielnie/templates/artykuly.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <br><br>
    <table class="table">
        <thead>
          <tr>
            <th>lp</th>
            <th>typ</th>
            <th>temat</th>
            <th>data</th>
            <th>opis</th>
            <th>odnosniki</th>
            <th>spółdzielnia</th>
            <th>miejscowość</th>
            
          </tr>
        </thead>
  
      </table>
    <div id="sprawy">

    </div>
    <div>

    </div>
</div>
<script type="module">


    // var spoldzielnie = d3.csv("{{ url_for('static', filename='warszawskie_spoldzielnie.csv') }}")


    var artykuly = d3.json({{ url_for("common.artykuly_dane") | tojson }})


    var formatMoney = d3.formatMoney = function (d) { return d3.format(",.2f")(d) + " zł"; }
    var d_parse = d3.utcParse("%a, %d %b %Y %H:%M:%S GMT")
    var d_format = d3.utcFormat("%Y-%m-%d")

    Promise.all([ artykuly]).then(function([artykuly]){  



            // Sort artykuly by data_poczatkowa
         artykuly =    artykuly.sort(function(a, b) {
    return new Date(d_parse(b.data_rozpoczenia)) - new Date(d_parse(a.data_rozpoczenia));
});

console.log(artykuly);

        let tabela = d3.select("table")

        let wiersz = tabela.append("tbody")
        .selectAll("tr").data(artykuly)
        .enter()
        .append("tr")
        // .attr("id", function(d) {return d.krs})
        .attr('class', 'artykuly')


        wiersz.append("td")
        .html(function (d,i) { return (i+1)+"." })



        wiersz.append("td")
        .html(function (d,i) { return d.typ })
        wiersz.append("td")
        .html(function (d,i) { return d.temat })



        wiersz.append("td")
        .text(function (d) { return d_format(d_parse(d.data_rozpoczenia)) })

        wiersz.append("td")
        .html(function (d,i) { return d.opis })

        // wiersz.append("td")
        // .html(function (d,i) { return d.odnosniki.split("|")})

        wiersz.append("td")
        .selectAll("a")
        .data(function(d){return d.odnosniki.split("|")})
        .enter()
        .append("a")
        .attr("href",function(d){return d})
        .attr("target","_blank")
        .attr("rel", "noopener noreferrer")
        .text(function(d,i){return 'odnośnik_'+(i+1)+'.'})
        .append("br")


        wiersz.append("td")
        .html(function (d,i) { return d.nazwa })

        wiersz.append("td")
        .html(function (d,i) { return d.miejscowosc })
        // sprawy.append("div")
        //     .attr("class","column")
        //     .selectAll("p")
        //     .data(function(d){return d.odnosniki.split("|")})
        //     .enter()
        //     .append("p")
        //     .attr("style", "font-size: 14px; margin-bottom: 14px;")
        //     .append("a")
        //     .attr("href",function(d){return d})
        //     .text(function(d){return d})      


            // split d.odnosniki by |
            // sprawy.append("div")
            // .attr("class","column")
            // .selectAll("p")
            // .data(function(d){return d.odnosniki.split("|")})
    })


</script>
{% endblock %}

pkgs/spoldzielnie/src/spoldzielnie/templates/base.html
<!doctype html>
<html>

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<script src="{{ url_for('static', filename='d3.v7.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/@turf/turf@6/turf.min.js"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.css')}}">
<link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='favicon.png') }}" >
<title>Warszawskie spółdzielnie mieszkaniowe</title>
<style>

.continent {
    fill: url(#svgGradient);
    stroke: #e9df58;
    stroke-width: 0px;
}

.dzielnice {
    /* fill: rgb(230, 199, 96); */
    fill: none;
    stroke: #5f2848;
    stroke-width: 1px;
}

.dzielnica {
    /* fill: rgb(230, 199, 96); */
    fill: none;
    stroke: #5f2848;
    stroke-width: 3px;
}



.dzialki {
    /* fill: rgb(230, 199, 96); */
    fill: rgb(230, 248, 148);
    stroke: #05c024;
    stroke-width: 1px;
}

.wisla {
    fill: none;
    stroke: #a3b9ff;
    stroke-width: 10px;
}

.drogi {
    fill: none;
    stroke: #d76050;
    stroke-width: px;
}


.labels {
    font-family: sans-serif;
    font-size: 11px;
    fill: #3c373d;
}

p.title {
/* text-shadow:
    2px 2px 2px #d6693d;
    2px 2px 1px red; */
    background-color: #ffffff;



}

p.subtitle {
  color: #ffffff;
/* text-shadow:
    2px 1px 1px rgb(103, 66, 104),
    2px 2px 1px red; */
    background-color: #e07f7f;
width:246px;
}



tr.spoldzielnia{
    color: black;
    background-color: rgb(147, 230, 255);
}


tr.spoldzielnia_grunty{
    color: black;
    background-color: rgb(0, 154, 201);
}

div.info-nadtabela {
    background-color: #d8e6e9;
    color: rgb(0, 0, 0);
    padding: 10px;
    margin: 20px;
    border-radius: 10px;

}

line.gridline {
    fill: none;
    stroke-width: 1px;
    stroke: black;
    border-style: dotted;
    stroke-dasharray: 5;
  }

</style>
</head>

<body>
    <section class="hero">
        <div class="container is-widescreen">
        <div class="hero-body">
          <p class="title is-size-1">
              warszawskie spółdzielnie mieszkaniowe
          </p>
          <!-- <p class="subtitle">&nbsp;&nbsp;
            <div id="svgEmbed"></div>
          </p> -->
        </div>
    </div>
    </section>
    <section>

    <div class="container is-widescreen">
    <nav class="breadcrumb is-centered" aria-label="breadcrumbs">
        <ul>
          <li><a href="{{ url_for('common.main')}}">Grafiki</a></li>
          <li><a href="{{ url_for('common.spoldzielnie')}}">Spółdzielnie</a></li>
          <li><a href="{{ url_for('common.artykuly')}}">Artykuły</a></li>

        </ul>
      </nav>
    </div>  
      </section>
      <section>

        <div class="container is-widescreen">
            <br><br>
        </div>
    </section>
      {% block content %}{% endblock %}
      <footer class="footer">
        <div class="content has-text-centered">
          <p>
            <strong>warszawskie spółdzielnie mieszkaniowe</strong> [wersja 2024-08-09]
    </p>

        </div>
      </footer>
    </body>
    </html>

pkgs/spoldzielnie/src/spoldzielnie/templates/index.html
{% extends 'base.html' %}
{% block content %}

<section>
    <div class="container is-widescreen">
        <div class="columns is-multiline" id="wszystko">

        </div>
    </div>

    <div class="container is-widescreen">
        <br><br>
    </div>
</section>
<script type="module">
    import { wykres_spoldzielni, daj_mi_wykres, pogrupuj, pogrupuj2, wykres_dzielnica } from '{{ url_for("static", filename="charts.js")}}';

    var w = 700;
    var h = 700;

    //d3.select("div#wszystko").append("div").attr("class", "cell").node().appendChild(
    var svg = d3.select("div#wszystko").append("div").attr("class", "cell").append("svg").attr("width", w).attr("height", h)
        .attr("viewBox", "0 0 " + w + " " + h).style("background", "#fffaaf");

    var projection = d3.geoMercator().translate([w / 2 - 100, h / 2 + 570]).scale(86000).center([21, 52]);
    var path_proj = d3.geoPath().projection(projection);

    var warszawa = d3.json("{{ url_for('static', filename='dzielnice/warszawa.geojson') }}")
    var warszawa_dzielnice = d3.json("{{ url_for('static', filename='dzielnice/warszawa-dzielnice.geojson') }}")
    var wisla = d3.json("{{ url_for('static', filename='dzielnice/wisla.geojson') }}")
    var warszawa_drogi = d3.json("{{ url_for('static', filename='dzielnice/warszawa_drogi2ba.geojson') }}")


    var spoldzielnie = d3.json({{ url_for("common.spoldzielnie_dane") | tojson }})
    var sprawy = d3.json({{ url_for("common.sprawy_dane") | tojson }})
    var gw_svg = d3.svg("{{ url_for('static', filename='pics/gwiazdka2.svg') }}")


    // var formatMoney = function (d) { return d3.format(".2f")(d) + " zł"; }


    // change formatMoney to separate thousands with space
    var formatMoney = d3.formatMoney = function (d) { return d3.format(",.2f")(d) + " zł"; }


    function fixCoordinatesOrder(geojson) {
        geojson.features.forEach(feature => {
            if (feature.geometry.type === "Polygon") {
                feature.geometry.coordinates.forEach((ring, i) => {
                    if (i === 0) {
                        // Exterior ring should be counter-clockwise
                        if (d3.polygonArea(ring) < 0) {
                            ring.reverse();
                        }
                    } else {
                        // Interior rings (holes) should be clockwise
                        if (d3.polygonArea(ring) > 0) {
                            ring.reverse();
                        }
                    }
                });
            } else if (feature.geometry.type === "MultiPolygon") {
                feature.geometry.coordinates.forEach(polygon => {
                    polygon.forEach((ring, i) => {
                        if (i === 0) {
                            // Exterior ring should be counter-clockwise
                            if (d3.polygonArea(ring) < 0) {
                                ring.reverse();
                            }
                        } else {
                            // Interior rings (holes) should be clockwise
                            if (d3.polygonArea(ring) > 0) {
                                ring.reverse();
                            }
                        }
                    });
                });
            }
        });
        return geojson;
    }

    let dzielniceWarszawy = [];

    Promise.all([warszawa,
        wisla,
        spoldzielnie,
        warszawa_dzielnice,
        warszawa_drogi])
        .then(function ([
                warszawa,
                wisla,
                spoldzielnie,
                warszawa_dzielnice,
                warszawa_drogi]) {

                spoldzielnie.sort(function (a, b) {
                    return b.bilans - a.bilans;
                });

                var defs = svg.append('defs');
                var gradient = defs.append('linearGradient')
                    .attr('id', 'svgGradient')
                    .attr('x1', '0%')
                    .attr('x2', '100%')
                    .attr('y1', '0%')
                    .attr('y2', '100%');

                gradient.append('stop')
                    .attr('class', 'start')
                    .attr('offset', '0%')
                    .attr('stop-color', '#ca554a')
                    .attr('stop-opacity', 0.0);

                gradient.append('stop')
                    .attr('class', 'end')
                    .attr('offset', '100%')
                    .attr('stop-color', '#cada14')
                    .attr('stop-opacity', 0);

                // dzielnice = ["Bemowo", "Białołęka", "Bielany", "Mokotów", "Ochota", "Praga-Południe", "Praga-Północ", "Rembertów", "Śródmieście", "Targówek", "Ursus", "Ursynów", "Wawer", "Wesoła", "Wilanów", "Włochy", "Wola", "Żoliborz"];

                
                warszawa_dzielnice.features.forEach(function (feature) {

                    if (feature.properties.name != "Warszawa") {
                        dzielniceWarszawy.push(feature.properties.name)
                    }


                    feature.geometry.coordinates.forEach(function (coords) {
                        coords.forEach(function (coord) {
                            coord.reverse();
                        });
                    });

                });

                svg.selectAll("path.drogi")
                    .data(warszawa_drogi.features)
                    .enter()
                    .append("path")
                    .attr("class", "drogi")
                    .attr("d", path_proj);

                svg.selectAll("path.dzielnice")
                    .data(warszawa_dzielnice.features)
                    .enter()
                    .append("path")
                    .attr("class", "dzielnice")
                    .attr("d", path_proj);

                svg.selectAll("path.wisla")
                    .data(wisla.features)
                    .enter()
                    .append("path")
                    .attr("class", "wisla")
                    .attr("d", path_proj);



                let g_spol = svg.selectAll("g.spoldzielnia")
                    .data(spoldzielnie)
                    .enter()
                    .append("g")
                    .attr("class", "spoldzielnia")
                    .attr("transform", function (d) {
                        return "translate(" + projection([d.dlugosc_geo, d.szerokosc_geo]) + ")"
                    })



                spoldzielnie = spoldzielnie.map(function (d) {
                    d.bilans_rsquare = Math.sqrt(parseFloat(d.bilans)) // Replace "value" with the value you want to assign to the new attribute
                    return d;
                });

                const max_bilans = d3.max(spoldzielnie, function (d) { return d.bilans_rsquare; })
                const min_bilans = d3.min(spoldzielnie, function (d) { return d.bilans_rsquare; })



                var r_bilans = d3.scaleLinear()
                    .domain([0, max_bilans])
                    .range([3, 16]);

                g_spol
                    .append("circle")
                    .attr("class", "spoldzielnia")
                    .attr("cx", 0)
                    .attr("cy", 0)
                    .attr("r", function (d) {
                        let rr = 0
                        // if (d.bilans_rsquare > 0) {
                        //    rr = d.bilans_rsquare
                        // } 
                        // return r_bilans(rr)
                        return 4;
                    }
                    )
                    .attr("fill", function (d) {
                        return 'rgb(147, 230, 255)'

                    })
                    .attr("stroke", "black")
                    .attr("stroke-width", 1)
                    .attr("opacity", 0.7)

                svg.append('rect')
                    .attr('x', 0)
                    .attr('y', 0)
                    .attr('width', w)
                    .attr('height', h)
                    .style('fill', 'none')
                    .style('stroke', '#d76050')
                    .style('stroke-width', 2);


                function resolveRandom(dzielnica) {
     
                    return new Promise((resolve) => {
                        setTimeout(() => {
                        resolve(" slow "+ dzielnica);
                        
                        }, Math.floor(Math.random() * 3000));
                    });
}

                async function dodaj_dzielnie(dzielnica) {

                    var featureDzielnica =  await warszawa_dzielnice.features.find(feature => feature.properties.name === dzielnica);
                    var spoldzielnieDzielnica =  spoldzielnie.filter(feature => feature.dzielnica === dzielnica);

                    let roadsWithinAdminUnit = warszawa_drogi.features.filter(function (road) {
                        return turf.booleanWithin(road, featureDzielnica);
                    });

                    let dzielnica_drogi = {
                        type: "FeatureCollection",
                        features: roadsWithinAdminUnit
                    };

                    let wazna = await resolveRandom(dzielnica);
                

                    d3.select("div#wszystko").append("div").attr("class", "cell").node().appendChild(
                        wykres_dzielnica(
                            featureDzielnica,
                            dzielnica,
                            await spoldzielnieDzielnica,
                            dzielnica_drogi));
                    

                }

                async function loadAllMaps(dzielnice_warszawy) {

                    const loadPromises = dzielnice_warszawy.map(dzielnica => dodaj_dzielnie(dzielnica));

                    return Promise.all(loadPromises);
                }


                loadAllMaps(dzielniceWarszawy).then(() => {
                    // console.log("All maps loaded");


                    let dane_w = pogrupuj(spoldzielnie);
                    let suma_wszystkich = d3.sum(spoldzielnie, function (d) { return d.bilans; });
                    let wyk = daj_mi_wykres(dane_w, 'Rys. Suma bilansów SM za rok 2022, wg dzielnic.');


                    //d3.select("div#wszystko").append("div").attr("class", "cell").node().appendChild(
                    d3.select("div#wszystko").append("div").attr("class", "cell").node().appendChild(wyk);

                    let dane_w2 = pogrupuj2(spoldzielnie);
                    let wyk2 = daj_mi_wykres(dane_w2, 'Rys. Liczba SM według dzielnic.');

                    d3.select("div#wszystko").append("div").attr("class", "cell").node().appendChild(wyk2);



                });



   
                    
       



        });




</script>
{% endblock %}

pkgs/spoldzielnie/src/spoldzielnie/templates/spoldzielnia.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <br><br>
    <div class="table-container">
        <div class="info-nadtabela">
      <p><i>Poniższa lista może być niezupełna lub nieaktualna.</i></p>
    </div>
    <table class="table">
        <thead>
          <tr>
            <th>lp</th>
            <th>Nazwa</th>
            <th>KRS</th>

            <!-- <th>Sprawy</th> -->
            <th>Adres</th>
            <th>Bilans 2022</th>

            
          </tr>
        </thead>
  
      </table>
    </div>
</div>
<script type="module">

var warszawa = d3.json("{{ url_for('static', filename='dzielnice/warszawa.geojson') }}")
    var warszawa_dzielnice = d3.json("{{ url_for('static', filename='dzielnice/warszawa-dzielnice.geojson') }}")
    var wisla = d3.json("{{ url_for('static', filename='dzielnice/wisla.geojson') }}")

    // var spoldzielnie = d3.csv("{{ url_for('static', filename='warszawskie_spoldzielnie.csv') }}")


    var spoldzielnie = d3.json({{ url_for("common.spoldzielnie_dane") | tojson }})
    var sprawy = d3.json({{ url_for("common.sprawy_dane") | tojson }})
    var gw_svg = d3.svg("{{ url_for('static', filename='pics/gwiazdka2.svg') }}")

    var formatMoney = d3.formatMoney = function (d) { return d3.format(",.2f")(d) + " zł"; }

    Promise.all([warszawa, wisla, spoldzielnie, gw_svg, sprawy, warszawa_dzielnice]).then(function(values){  



        let tabela = d3.select("table")

        let wiersz = tabela.append("tbody")
                      .selectAll("tr")
                      .data(values[2])
                      .enter()
                      .append("tr")
                      .attr("id", function(d) {return d.krs})
                      .attr('class', 'spoldzielnia')


        wiersz.append("td")
        .html(function (d,i) { return (i+1)+"." })

        wiersz.append("td")
        .html(function (d,i) { return "&#9679; " + d.nazwa })



        wiersz.append("td")
        .text(function (d) { return d.krs })


        wiersz.append("td")
        .text(function (d) { return d.adres.toUpperCase()+", "+d.kod_pocztowy+", "+d.miejscowosc.toUpperCase() + " ("+d.dzielnica.toUpperCase()+")"})

        wiersz.append("td")
        .text(function (d) { 
            
            if (d.bilans == "NaN" || d.bilans == "nan" || d.bilans==0 || d.bilans == "" || d.bilans == null) {
                return "brak danych";
            }
            else if (d.bilans == "do sprawdzenia") {
              return "do sprawdzenia";
            }
            else{
                return formatMoney(d.bilans);
            }             
             })



        // d3.selectAll("tbody").append("tr","tr")

        // const formatTime = d3.utcFormat("%Y-%m-%d");

        // values[4].forEach(function(sprawa) {
           


        //     var x = document.getElementById(sprawa.spoldzielnia);
        //     let t = document.createElement('tr');
        //     x.parentNode.insertBefore(t, x.nextSibling);  

        //     // get string from date object sprawa.data_rozpoczenia
        //     let data_rozpoczenia = formatTime(new Date(sprawa.data_rozpoczenia));

        //     let ih = "<td></td><td>&#9733; "+sprawa.kategoria+"</td><td>("+data_rozpoczenia+") "+sprawa.opis+"</td><td></td>"

            

        //       t.ih += "<td>"
            
        //     let odnosniki = sprawa.odnosniki.split("|");
        //     odnosniki.forEach(function(odnosnik) {
        //         ih += "<a href='"+odnosnik+"'>"+odnosnik+"</a><br><br>"
              
        //     });
        //     ih += "</td>"

        //     t.innerHTML = ih;
  
    
        // })

    })


</script>
{% endblock %}